### PR TITLE
Feature/buttons in upper right corner

### PR DESCRIPTION
**Pull request by sergeyepimakhov**
Hi there, thought it's a good idea to place control buttons to the upper right corner of the cell, that could improve the usability. I combined also the both buttons Run and Restart into a button group. I did't find any issue concerning that. May be you can help me if you know any.

Cheers!

### CODE REVIEW

**Comment by choldgraf** [comment]
Hey there, this looks interesting! could you post screenshots of what this changes visually? Or perhaps links to a website with these changes in it?

**Comment by sergeyepimakhov** [comment]
image

**Comment by choldgraf** [comment]
I think it looks nice, though this one probably merits a discussion to get agreement on the best location. For example, why is it better to have the buttons in the code blocks rather than below in the output block?

Another option would be to make the location of the buttons configurable, so users could choose what they wish. In that case it’d probably be best to make the current behavior the default though

**Comment by sergeyepimakhov** [comment]
I find the idea to make the location of the buttons configurable very promising. Let me think about that.

**Comment by choldgraf** [comment]
Sounds good - though it's probably best to get some consensus from the community before doing a ton of work in implementation. Not sure who else should weigh in, but probably @minrk at least

**Pull request closed without merging**
