### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by joelachance**
There were some vulnerabilities after running `npm audit`, so this fixes some of those. In addition, there was some unused code removed as well.

### CODE REVIEW

**Comment by joelachance** [comment]
Ah, it looks like efforts were duplicated in PR #186. Either PR should be merged due to vulnerabilities.
@minrk @choldgraf

**Comment by choldgraf** [comment]
Is there some way we can confirm that this still works as-expected? Did you test on your fork? Wanna rebase on master so that I can demo this with your nifty new developer preview code?

**Comment by choldgraf** [comment]
I just tested this locally, and am noticing that some CSS rules don't seem to be applied properly. Here's the example from the main docs:

image

Do you think that's just because the other CSS rules from the documentation pages aren't loaded?

**Comment by joelachance** [comment]
> Is there some way we can confirm that this still works as-expected? Did you test on your fork? Wanna rebase on master so that I can demo this with your nifty new developer preview code?

It seemed to work as expected, but I will rebase on master! On that note, I'm indifferent about removing the unused code here. It may be more of a risk than is necessary.

I do think its worth merging the dependency change due to vulnerabilities.

> I just tested this locally, and am noticing that some CSS rules don't seem to be applied properly. Here's the example from the main docs:

I'm going to look at this today-- I have a feeling this is due to some styling I put into the development.html file, and not Thebelab.

It'll be best for you to test it again quick after we make changes as I'm not 100% how everything should look & function just yet.

**Comment by joelachance** [comment]
This got messy. I'm going to PR a change for the height fix, and then we might as well use this PR for the dependency update: https://github.com/minrk/thebelab/pull/186/files

I vote for not including the unused code removal commits for now.

**Pull request closed without merging**
